version: 2

builds:
- id: kv-client
  main: .              # this folder has go.mod + main.go
  binary: kv-client
  env: [CGO_ENABLED=0]
  goos: [linux, darwin, windows]
  goarch: [amd64, arm64]

archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: "checksums.txt"
